export const diveLevelOptions = [
    '0',
    'новичок',
    'ноль', 
    'начальный, без сертификата',
    'отсутствует',
    'интро',
    'пробовал пару раз',
    'на открытую воду',
    'реферал',
    'скуба дайвер',
    'опен вотер',
    'опёнок',
    'эдванс',
    'адванс',
    'рескью',
    'дайвмастер',
    'ассистент',
    'инструктор',
    'дайв-лидер',
    'найтрокс',
    'дип',
    'эдванс найтрокс',
    'деко про',
    'технический дайвер',
    'нормоксик тримикс дайвер',
    'тримикс дайвер',
    'ребризер',
    'OWD',
    'Open water diver PADI',
    'AOWD',
    'Advanced open water diver PADI',
    'Rescue diver PADI',
    'DM',
    'Divemaster PADI',
    'Assistant instructor PADI',
    'Instructor PADI',
    'OWSI',
    'MSDT',
    'IDC Staff',
    'Advanced nitrox',
    'Deco pro',
    'Technical diver',
    'Normoxic trimix diver',
    'Trimix diver',
    'rebreather',
    '* CEDIP',
    'CEDIP 1*',
    '* UDIP',
    'UDIP 1*',
    '* CMAS',
    'CMAS 1*',
    '** CEDIP',
    'CEDIP 2*',
    '** UDIP',
    'UDIP 2*',
    '** CMAS',
    'CMAS 2*',
    '*** CEDIP',
    'CEDIP 3*',
    '*** UDIP',
    'UDIP 3*',
    '*** CMAS',
    'CMAS 3*',
    'одна звезда',
    'две звезды',
    'три звезды',
    'Novice diver',
    'Diver NDL',
    'Universal diver NDL',
    'Advanced universal diver NDL',
    'Rescue diver NDL',
    'Divemaster NDL',
    'Diveleader NDL',
    'Instructor NDL rank I',
    'Instructor NDL rank II',
    'Instructor NDL rank III',
    'Nitrox diver',
    'Deep diver'
]

